### ISSUE TITLE
ConcurrentModificationException: null while opening PyCharm

### ISSUE THREAD

**Issue by jcdevil** [deepsky/SQL-Code-Assistant-#12]
Error while opening PyCharm (1 Oracle datasource had previously been defined): 

Environment : Windows 7 x64
Information got from Help/About of PyCharm :
PyCharm version 3.1.3
JRE : 1.7.0_40_b43 x86

Please let me know if over information are required :)
Cheers
JC Deville

null
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
    at java.util.HashMap$EntryIterator.next(HashMap.java:966)
    at java.util.HashMap$EntryIterator.next(HashMap.java:964)
    at com.deepsky.lang.plsql.resolver.index.IndexTreeBase.iterateTopNodes(IndexTreeBase.java:972)
    at com.deepsky.navigation.impl.NameLookupServiceImpl.updateCache(NameLookupServiceImpl.java:129)
    at com.deepsky.navigation.impl.NameLookupServiceImpl.access$300(NameLookupServiceImpl.java:62)
    at com.deepsky.navigation.impl.NameLookupServiceImpl$IndexManagerListenerImpl$1.run(NameLookupServiceImpl.java:429)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:346)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by deepsky** [comment]
Thanks, JC Deville, I'll look into it.
Regards,
Serhiy
