### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mcormier** [deepsky/SQL-Code-Assistant-#14]
Running IDEA 13.1

-1: -1
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.Vector.elementData(Vector.java:730)
    at java.util.Vector.get(Vector.java:746)
    at com.deepsky.lang.plsql.completion.logic.TreePathImpl$1.next(TreePathImpl.java:54)
    at com.deepsky.lang.plsql.completion.logic.TreePathImpl$1.next(TreePathImpl.java:44)
    at com.deepsky.lang.plsql.completion.syntaxTreePath.generator.TreePathIteratorImpl$State.<init>(TreePathIteratorImpl.java:145)
    at com.deepsky.lang.plsql.completion.syntaxTreePath.generator.TreePathIteratorImpl.<init>(TreePathIteratorImpl.java:41)
    at com.deepsky.lang.plsql.completion.syntaxTreePath.generated.CompletionProcessorBase$1.<init>(CompletionProcessorBase.java:46)
    at com.deepsky.lang.plsql.completion.syntaxTreePath.generated.CompletionProcessorBase.<init>(CompletionProcessorBase.java:46)
    at com.deepsky.lang.plsql.completion.syntaxTreePath.generated.CompletionProcessor2.<init>(CompletionProcessor2.java:828)
    at com.deepsky.lang.plsql.completion.MyCompletionContributor.fillCompletionVariants(MyCompletionContributor.java:93)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:75)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:769)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$900(CompletionProgressIndicator.java:84)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:751)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:911)
    at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)

**Comment by deepsky** [comment]
Hi.
I would appreciate if you could provide more information about the issue, i.e. JetBrains product, version number, sql or plsql code which brought the issue.

Regards,
Serhiy

**Comment by mcormier** [comment]
Sorry Serhiy, I don't recall what I was editing or have a reproducer for you.

**Comment by mcormier** [comment]
The exact IntelliJ build number was 135.1019 (June 4th 2014) EAP

I just upgraded to 135.1230 and will let you know if I encounter this issue again.

**Comment by deepsky** [comment]
Thanks, Matthieu!

Serhiy
