### ISSUE TITLE
IDE Fatal Error in JetBrains

### ISSUE THREAD

**Issue by kidplug** [deepsky/SQL-Code-Assistant-#15]
Got an error/alert in JetBrains.  Popup says to report the problem to you.

```
Error while indexing C:\Users\chapman\git_checkout\arcos-app\arcos10-plsql\lib\pljson\setup_json_user.sql
To reindex this file IDEA has to be restarted: com/intellij/openapi/editor/DefaultLanguageHighlighterColors
java.lang.NoClassDefFoundError: com/intellij/openapi/editor/DefaultLanguageHighlighterColors
    at com.deepsky.lang.plsql.highlighter.DefaultHighlighter.<clinit>(DefaultHighlighter.java:36)
    at com.deepsky.lang.plsql.highlighter.PlSqlHighlighterBase.<clinit>(PlSqlHighlighterBase.java:92)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:62)
    at com.intellij.openapi.util.KeyedExtensionFactory.getByKey(KeyedExtensionFactory.java:82)
    at com.intellij.openapi.util.KeyedExtensionFactory.access$000(KeyedExtensionFactory.java:32)
    at com.intellij.openapi.util.KeyedExtensionFactory$1.invoke(KeyedExtensionFactory.java:48)
    at $Proxy50.create(Unknown Source)
    at com.intellij.openapi.fileTypes.FileTypeEditorHighlighterProviders$1.getEditorHighlighter(FileTypeEditorHighlighterProviders.java:49)
    at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:81)
    at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:121)
    at com.intellij.ide.highlighter.HighlighterFactory.createHighlighter(HighlighterFactory.java:39)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:171)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:149)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:107)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:99)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
    at com.intellij.util.indexing.FileBasedIndexImpl$24.run(FileBasedIndexImpl.java:1702)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeNonCancelableSection(ProgressManagerImpl.java:139)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1698)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1664)
    at com.intellij.util.indexing.UnindexedFilesUpdater.processFile(UnindexedFilesUpdater.java:68)
    at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:102)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:228)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.editor.DefaultLanguageHighlighterColors PluginClassLoader[SQL, 1.6.1.129]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 36 more



java.lang.ClassNotFoundException: com.intellij.openapi.editor.DefaultLanguageHighlighterColors PluginClassLoader[SQL, 1.6.1.129]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at com.deepsky.lang.plsql.highlighter.DefaultHighlighter.<clinit>(DefaultHighlighter.java:36)
    at com.deepsky.lang.plsql.highlighter.PlSqlHighlighterBase.<clinit>(PlSqlHighlighterBase.java:92)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:62)
    at com.intellij.openapi.util.KeyedExtensionFactory.getByKey(KeyedExtensionFactory.java:82)
    at com.intellij.openapi.util.KeyedExtensionFactory.access$000(KeyedExtensionFactory.java:32)
    at com.intellij.openapi.util.KeyedExtensionFactory$1.invoke(KeyedExtensionFactory.java:48)
    at $Proxy50.create(Unknown Source)
    at com.intellij.openapi.fileTypes.FileTypeEditorHighlighterProviders$1.getEditorHighlighter(FileTypeEditorHighlighterProviders.java:49)
    at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:81)
    at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:121)
    at com.intellij.ide.highlighter.HighlighterFactory.createHighlighter(HighlighterFactory.java:39)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:171)
    at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:149)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:107)
    at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:99)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:215)
    at com.intellij.util.indexing.FileBasedIndexImpl$24.run(FileBasedIndexImpl.java:1702)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeNonCancelableSection(ProgressManagerImpl.java:139)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1698)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1664)
    at com.intellij.util.indexing.UnindexedFilesUpdater.processFile(UnindexedFilesUpdater.java:68)
    at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:102)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:228)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)




```

**Comment by kidplug** [comment]
Here is the file in question: setup_json_user.sql

```
-- GITHASH: GIT_HASH_ID run this as json user after user is created

!puf g_temp.sql code_version.sql updateVersion.sql arcos_logger.sql
@g_temp.sql 
@code_version.sql 
@updateVersion.sql 
@arcos_logger.sql

!rm g_temp.sql code_version.sql updateVersion.sql arcos_logger.sql

@invalid.sql

```

**Comment by kidplug** [comment]
Seems that specific file wasnt the issue.  I just restarted JetBrains and got the same error for a different source file.

I just installed the plugin today.
The version appears to be:  1.6.1.29

**Comment by deepsky** [comment]
Hello, I am wondering how did you manage to have it installed, the
plugin does not work under version 14 and 15.

**Comment by kidplug** [comment]
I just used the Plugin manager, and "browse" repositories.
Thanks for the reply.
