### ISSUE TITLE
Column Employee name not found

### ISSUE THREAD

**Issue by ser-lisenko** [deepsky/SQL-Code-Assistant-#4]
When I was connected to the db and the message was "Update user objects" throw this exception and the execution process of connecting had break. But the status progress in the window about execution was only stoped. 

Column Employee name not found: Column Employee name not found
java.lang.Error: Column Employee name not found
    at com.deepsky.database.ora.desc.OraTableDescriptor.getColumnDescriptor(OraTableDescriptor.java:86)
    at com.deepsky.database.ora.handlers.TableDefGenerator.generate(TableDefGenerator.java:56)
    at com.deepsky.database.ora.handlers.TableDefGenerator.generate(TableDefGenerator.java:230)
    at com.deepsky.database.ora2.loaders.TableLoader.load(TableLoader.java:352)
    at com.deepsky.database.ora2.DbCacheManager.makeUpdate(DbCacheManager.java:457)
    at com.deepsky.database.ora2.DbSchemaIndexer.run(DbSchemaIndexer.java:307)
    at java.lang.Thread.run(Thread.java:722)

**Comment by deepsky** [comment]
Thanks for reporting!

It looks like one of tables has a column name with a whitespace? Like this: 
create table t1 (
    "Employee name" varchar2(40)
);
Such way naming of column is valid but not encouraged by Oracle. Need to say the plugin does not support it now, but I will fix this issue in the next release which is scheduled on the next week.

**Comment by ser-lisenko** [comment]
Also in my project there is a lot of sql script. About 10000. And when i was start IDEA the working was freeze for some minutes. May be its is related with that your's plugin analyze all script in my project. How can i fix this?

**Comment by deepsky** [comment]
Yes, on the first start, the plugin parses and build index for all files in the source trees belongs to plugin's file type. This file type is specified in "Settings->File Types" under the name "SQL (PL/SQL) files". By default, plugin assigns "sql", "pks" and "pkb" file extensions to this file type, but you can edit the list of file extensions if you fill that some of the them are extra.
Coming back to parsing of scripts ... after building indexes a script will be re-parsed only if it is modified. So, after initial parsing, the plugin should not impact performance. Anyway, taking into account a chance to have 10K scripts in project it need to review indexing flow .....
